# X10SRL machine configuration

require conf/machine/include/aspeed.inc

KMACHINE = "aspeed"
KERNEL_DEVICETREE = "aspeed/aspeed-bmc-supermicro-x10srl.dtb"

UBOOT_MACHINE = "ast_g4_ncsi_config"

FLASH_SIZE = "32768"

MACHINE_FEATURES += "obmc-host-ipmi obmc-host-state-mgmt obmc-chassis-state-mgmt"

VIRTUAL-RUNTIME_skeleton_workbook = "${MACHINE}-config"

PREFERRED_PROVIDER_virtual/obmc-host-ipmi-hw = "phosphor-ipmi-kcs"
PREFERRED_PROVIDER_virtual/obmc-chassis-mgmt = "x86-power-control"
PREFERRED_PROVIDER_virtual/obmc-fan-mgmt = "phosphor-pid-control"
PREFERRED_PROVIDER_virtual/phosphor-led-manager-config-native = "x10srl-led-manager"

OBMC_MACHINE_FEATURES += "obmc-phosphor-fan-mgmt obmc-phosphor-event-mgmt obmc-phosphor-inventory-mgmt obmc-host-ipmi"
