# Layer configuration
BBPATH .= ":${LAYERDIR}"

BBFILES += "${LAYERDIR}/recipes-*/*/*.bb ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-supermicro-x10srl"
BBFILE_PATTERN_meta-supermicro-x10srl = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-supermicro-x10srl = "10"

LAYERDEPENDS_meta-supermicro-x10srl = "core openembedded-layer phosphor-layer"
LAYERSERIES_COMPAT_meta-supermicro-x10srl = "kirkstone langdale mickledore nanbield scarthgap"
